name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e .[dev,llm]
      - run: python -m compileall -q neurodungeon
      - run: mypy --strict neurodungeon
      - run: pytest -q -m "not docker"

  docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      DOCKER_HOST: tcp://localhost:2375
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: docker info
      - run: pip install -e .[dev,llm]
      - run: mypy --strict neurodungeon
      - run: pytest -q
