name: CI
on:
  pull_request:
    branches: [ work ]
  push:
    branches: [ work ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install hypothesis pytest mypy
      - name: Static type check
        run: mypy --strict neurodungeon
      - name: Test suite
        run: pytest -q
